set -euo pipefail

# Generate deterministic PCB review artifacts for CI pull requests.
#
# Outputs are written under reports/review and are intended for human review:
# schematic PDF/SVG and 2D board PDFs/SVGs. STEP/GLB model exports and PNG 3D
# renders are intentionally generated by separate local tools because KiCad's 3D
# export paths are slow in CI.

review_dir="reports/review"
schematic_dir="$review_dir/schematic"
board_dir="$review_dir/board"

rm -rf "$review_dir"
mkdir -p "$schematic_dir/svg" "$board_dir/pdf" "$board_dir/svg"

echo "::group::Schematic review exports"
kicad-cli sch export pdf \
  --exclude-pdf-property-popups \
  --output "$schematic_dir/EveningStar-schematic.pdf" \
  pcb/EveningStar.kicad_sch
kicad-cli sch export svg \
  --output "$schematic_dir/svg" \
  pcb/EveningStar.kicad_sch
echo "::endgroup::"

echo "::group::PCB 2D review exports"
kicad-cli pcb export pdf \
  --mode-single \
  --layers F.Cu,F.Mask,F.Silkscreen,F.Fab,Edge.Cuts \
  --output "$board_dir/pdf/EveningStar-front.pdf" \
  pcb/EveningStar.kicad_pcb
kicad-cli pcb export pdf \
  --mode-single \
  --mirror \
  --layers B.Cu,B.Mask,B.Silkscreen,B.Fab,Edge.Cuts \
  --output "$board_dir/pdf/EveningStar-back.pdf" \
  pcb/EveningStar.kicad_pcb
kicad-cli pcb export pdf \
  --mode-multipage \
  --layers F.Cu,In1.Cu,In2.Cu,B.Cu,F.Silkscreen,B.Silkscreen,F.Fab,B.Fab,Edge.Cuts \
  --output "$board_dir/pdf/layers" \
  pcb/EveningStar.kicad_pcb

kicad-cli pcb export svg \
  --mode-single \
  --fit-page-to-board \
  --layers F.Cu,F.Mask,F.Silkscreen,F.Fab,Edge.Cuts \
  --output "$board_dir/svg/EveningStar-front.svg" \
  pcb/EveningStar.kicad_pcb
kicad-cli pcb export svg \
  --mode-single \
  --fit-page-to-board \
  --mirror \
  --layers B.Cu,B.Mask,B.Silkscreen,B.Fab,Edge.Cuts \
  --output "$board_dir/svg/EveningStar-back.svg" \
  pcb/EveningStar.kicad_pcb
echo "::endgroup::"

find "$review_dir" -type f | sort
