name: Checks

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    name: Nix checks
    runs-on: ubuntu-24.04
    env:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Cachix
        if: ${{ vars.CACHIX_CACHE_NAME != '' }}
        uses: cachix/cachix-action@v17
        with:
          name: ${{ vars.CACHIX_CACHE_NAME }}
          authToken: ${{ env.CACHIX_AUTH_TOKEN }}
          skipPush: ${{ env.CACHIX_AUTH_TOKEN == '' }}

      - name: Run checks
        run: nix run .#checks

      - name: Upload KiCad reports
        if: ${{ always() && hashFiles('reports/*.rpt') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: kicad-rule-check-reports
          path: reports/*.rpt
          if-no-files-found: error
